server:
  port: 8087

spring:
  application:
    name: backend
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
    auto-mapping-unknown-column-behavior: none
  type-aliases-package: >
    com.takoyakki.backend.domain.mentoring.dto.reservation,
    com.takoyakki.backend.domain.mentoring.dto.mentoring
  mapper-locations: classpath:mapper/**/*.xml
