server:
  port: 8087
spring:
  sql:
    init:
      schema-locations: classpath:schema.sql
      encoding: UTF-8
  application:
    name: backend
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
    auto-mapping-unknown-column-behavior: none
  mapper-locations: mapper/*.xml