server:
  port: 808
spring:
  application:
    name: backend
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
mybatis:
  mapper-locations: mapper/*.xml
  config-location: classpath:/mybatis-config.xml
jwt:
  secret: yourSecretKey123456789012345678901234567890