server:
  port: 8087
spring:
  application:
    name: backend
  datasource:
    driverClassName:
    url:
    username:
    password:
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
    auto-mapping-unknown-column-behavior: none
  mapper-locations: mapper/*.xml