server:
  port: 8087
spring:
  config:
    import: optional:application-secret.yml
  sql:
    init:
      schema-locations: classpath:schema.sql
      encoding: UTF-8
  application:
    name: backend
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  config-location: classpath:/mybatis-config.xml
jwt:
  secret: yourSecretKey123456789012345678901234567890
logging:
  level:
    com.takoyakki.backend: DEBUG
    org.mybatis: DEBUG
    org.mybatis.spring.SqlSessionFactoryBean: DEBUG
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    java.sql.PreparedStatement: DEBUG
    com.p6spy: DEBUG
p6spy:
  config:
    logMessageFormat: com.p6spy.engine.spy.appender.MultiLineFormat
    appender: com.p6spy.engine.spy.appender.Slf4JLogger
    logLevel: debug
anthropic:
  api:
    key: ${ANTHROPIC_API_KEY:not-defined}
