# display name
name: Docker Push Image

# trigger
on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: java checkout code
        uses: actions/checkout@v3

      
      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Create application-prod.yml
        run: |
          echo "${{ secrets.PROD_YML }}" > src/main/resources/application-prod.yml

      - name: grant permission
        run: chmod +x gradlew

      - name: build jar
        run: ./gradlew clean build -x test bootJar -Dspring.profiles.active=prod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/siat-git-action-backend:latest .

      - name: dockerhub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/siat-git-action-backend:latest

      # aws setting
      - name: Write docker-compose.yml on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/backend
            cat << 'EOF' > /home/ubuntu/backend/docker-compose.yml
            services:
              app:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/siat-git-action-backend:latest
                ports:
                  - "8087:8087"
                restart: always
            EOF

      - name: Deploy docker-compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/backend
            echo "컨테이너 중지"
            sudo docker compose down
            echo "이미지 삭제"
            sudo docker image prune -af
            sudo docker compose pull ${{ secrets.DOCKERHUB_USERNAME }}/siat-git-action-backend:latest
            sudo docker compose up -d  
            



            
